import { Poppins } from "next/font/google";
import "./globals.css";

const popins = Poppins({
  variable: "--popins",
  weight: ['100','200','300','400','600','700','800','900'],
  subsets: ["latin"],
});



export const metadata = {
  title: "Goblin",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${popins.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
